export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_EMPTY_ITEM = "CART_EMPTY_ITEM";
export const CART_LOADING_ITEM = "CART_LOADING_ITEM";
export const CART_LOADING_DEL_ITEM = "CART_LOADING_DEL_ITEM";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
